# Generated by Django 5.0.3 on 2024-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(blank=True, db_column='Time_Stamp', null=True)),
                ('comment_content', models.CharField(blank=True, db_column='Comment_Content', max_length=30, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeid', models.AutoField(db_column='LikeID', primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(blank=True, db_column='Time_Stamp', null=True)),
            ],
            options={
                'db_table': 'like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('noti_type', models.CharField(blank=True, db_column='Noti_Type', max_length=30, null=True)),
                ('time_stamp', models.DateTimeField(blank=True, db_column='Time_Stamp', null=True)),
                ('isread', models.CharField(blank=True, db_column='isRead', max_length=5, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(db_column='PostID', primary_key=True, serialize=False)),
                ('post_content', models.CharField(blank=True, db_column='Post_Content', max_length=200, null=True)),
                ('mediaurl', models.CharField(blank=True, db_column='MediaURL', max_length=50, null=True)),
                ('post_time_stamp', models.DateTimeField(blank=True, db_column='post_Time_stamp', null=True)),
                ('post_privacysetting', models.CharField(blank=True, db_column='post_PrivacySetting', max_length=30, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=30, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('passwordhash', models.CharField(blank=True, db_column='PassWordHash', max_length=50, null=True)),
                ('joindate', models.DateField(blank=True, db_column='JoinDate', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=40, null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('bio', models.CharField(blank=True, db_column='Bio', max_length=300, null=True)),
                ('profilepictureurl', models.CharField(blank=True, db_column='ProfilePictureUrl', max_length=100, null=True)),
                ('websiteurl', models.CharField(blank=True, db_column='WebsiteURL', max_length=100, null=True)),
                ('phonenumber', models.BigIntegerField(blank=True, db_column='PhoneNumber', null=True)),
                ('user_privacysetting', models.CharField(blank=True, db_column='user_PrivacySetting', max_length=50, null=True)),
                ('user_accountstatus', models.CharField(blank=True, db_column='user_AccountStatus', max_length=50, null=True)),
                ('user_accounttype', models.CharField(blank=True, db_column='user_AccountType', max_length=30, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
