# Generated by Django 5.0.3 on 2024-04-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
         migrations.RunSQL("""
            CREATE TRIGGER validate_email_trigger
            BEFORE INSERT ON user
            FOR EACH ROW
            BEGIN
             DECLARE email_pattern VARCHAR(255);
             SET email_pattern = '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$';
    
              IF NEW.email NOT REGEXP email_pattern THEN
                SET NEW.email = 'dash';  -- Set email to 'dash' if it's invalid
             END IF;
            END;
        """)
    ]
