# Generated by Django 5.0.3 on 2024-04-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_auto_20240420_1849'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE TRIGGER hash_password_trigger1
        BEFORE INSERT ON user
        FOR EACH ROW
        BEGIN
              SET NEW.passwordhash = SHA2(NEW.passwordhash, 256);
        END;
        """)
    ]
